### ISSUE TITLE
v3.0.1 failing with permissions issues

### ISSUE THREAD

**Issue by larowlan** [kss-node/kss-node#575]
Hi, after updating to 3.0.1 noticed our builds were failing with 

```
/data/node_modules/kss/node_modules/fs-extra/lib/mkdirs/make-dir.js:86
      } catch {
```

Downgrading to 3.0.0 fixed this.
Didn't look into it further, just felt I would flag in case someone else hits it.

**Comment by RobLoach** [comment]
Thanks for the catch!!!! pun completely intended....

What version of Node are you on? I'll see if there's some conflict with fs-extra. Thanks.

**Comment by larowlan** [comment]
v10 at this point

**Comment by charlieartist** [comment]
Can confirm @larowlan. Had same issue, with Node 8.9.1.

**Comment by flxa** [comment]
Pinning KSS to 3.0.0 worked for me. I will try adding `Twig.cache(false);` too. My error was 
```
Error parsing twig template home.twig: 
TypeError: file.includes is not a function
```

**Comment by j0k3r** [comment]
Same error here.
You can check the whole dump in that Travis log: https://travis-ci.org/github/20minutes/colette/jobs/680438827#L213

It only fail on the Node 8.10 build. Node 12 is working fine.

**Comment by hsnaydd** [comment]
> ```
> Error parsing twig template home.twig: 
> TypeError: file.includes is not a function
> ```

Same error here too 😕;

I am getting this error while using `embed` in the template files.

```twig
{#  Component Templete #}
{% embed "@components/card.html.twig" with {
    title: title,
    desc: desc,
} only %}
    {% block content %}
        <div class="c-join-us__title">{{ title }}</div>
        <p class="c-join-us__desc">{{ desc }}</p>
    {% endblock %}
{% endembed %}
```

```twig
{#  Styleguide Markup File #}
{% include "join-us.html.twig" with {
    title: "Lorem Ipsum!",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
  } only %}
```
